# Generated by Django 3.0.3 on 2020-02-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
