# Generated by Django 3.0.3 on 2020-03-04 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200229_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Type', verbose_name='Type'),
        ),
    ]
